"use client";
import { useMemo, useState } from "react";
import { Icon } from "@/components/ui/icons";
import { normalizeTiendanubeRows, parseTiendanubeCsv, TIENDANUBE_COLUMNS, type NormalizedTnProduct } from "@/lib/tiendanube-csv";

type ImportResult={products_new?:number;products_updated?:number;variants_new?:number;variants_updated?:number;errors?:string[]};
export default function TiendanubeImportClient({existingHandles,existingSkus}:{existingHandles:string[];existingSkus:string[]}){
  const [products,setProducts]=useState<NormalizedTnProduct[]>([]);const[fileName,setFileName]=useState("");const[columns,setColumns]=useState<string[]>([]);const[parseErrors,setParseErrors]=useState<string[]>([]);const[loading,setLoading]=useState(false);const[result,setResult]=useState<ImportResult|null>(null);
  const preview=useMemo(()=>{const hs=new Set(existingHandles);const ss=new Set(existingSkus);const allSkus=products.flatMap(p=>p.variants.map(v=>v.sku));const seen=new Set<string>();const duplicates=new Set<string>();for(const sku of allSkus){if(seen.has(sku))duplicates.add(sku);seen.add(sku)}return {newProducts:products.filter(p=>!hs.has(p.handle)).length,updatedProducts:products.filter(p=>hs.has(p.handle)).length,newVariants:allSkus.filter(s=>!ss.has(s)).length,updatedVariants:allSkus.filter(s=>ss.has(s)).length,duplicateSkus:[...duplicates],variants:allSkus.length}},[products,existingHandles,existingSkus]);
  async function loadFile(file:File){setResult(null);setFileName(file.name);const bytes=await file.arrayBuffer();const text=new TextDecoder("windows-1252").decode(bytes);const rows=parseTiendanubeCsv(text);const found=rows.length?Object.keys(rows[0]):[];setColumns(found);const missing=TIENDANUBE_COLUMNS.filter(c=>!found.includes(c));const normalized=normalizeTiendanubeRows(rows);const errors:string[]=[];if(missing.length)errors.push(`Faltan columnas esperadas: ${missing.join(", ")}`);if(!normalized.length)errors.push("No se detectaron productos válidos.");const skuMissing=normalized.flatMap(p=>p.variants).filter(v=>!v.sku).length;if(skuMissing)errors.push(`${skuMissing} variantes no tienen SKU.`);setParseErrors(errors);setProducts(normalized)}
  async function confirm(){if(!products.length||parseErrors.length)return;setLoading(true);setResult(null);try{const res=await fetch("/api/tiendanube/import",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({products})});const data=await res.json();if(!res.ok)throw new Error(data.error||"No se pudo importar");setResult(data)}catch(e){setResult({errors:[e instanceof Error?e.message:"Error inesperado"]})}finally{setLoading(false)}}
  return <div className="grid gap-4 xl:grid-cols-[1.4fr_.8fr]">
    <section className="pt-card p-4 sm:p-5"><div className="rounded-2xl border border-dashed border-[#e5b7ca] bg-[#fffafd] p-5 text-center"><div className="mx-auto flex h-11 w-11 items-center justify-center rounded-2xl bg-[#fff0f6] text-[#b84c79]"><Icon name="upload" /></div><p className="mt-3 font-bold text-[#4d2938]">Seleccioná el CSV exportado de Tiendanube</p><p className="mt-1 text-xs leading-5 text-[#8d6878]">No modifica la base hasta que confirmes la importación.</p><label className="pt-button-primary mt-4 inline-flex items-center justify-center px-5 text-sm">Elegir CSV<input type="file" accept=".csv,text/csv" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)void loadFile(f)}} /></label>{fileName&&<p className="mt-3 text-xs font-bold text-[#a83f6d]">{fileName}</p>}</div>
      {products.length>0&&<div className="mt-4"><div className="flex items-center justify-between"><h2 className="font-bold text-[#4d2938]">Vista previa</h2><span className="text-xs text-[#8d6878]">{products.length} productos · {preview.variants} variantes</span></div><div className="mt-3 max-h-[560px] space-y-2 overflow-y-auto pr-1">{products.map(p=><div key={p.handle} className="rounded-2xl border border-[#f0dce5] bg-white p-3"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate text-sm font-bold text-[#4d2938]">{p.name}</p><p className="mt-0.5 truncate text-[11px] text-[#8d6878]">{p.handle} · {p.category||"Sin categoría"}</p></div><span className="rounded-full bg-[#fff0f6] px-2 py-1 text-[10px] font-extrabold text-[#a83f6d]">{p.variants.length} variantes</span></div><div className="mt-2 flex flex-wrap gap-1.5">{p.variants.slice(0,6).map(v=><span key={v.sku} className="rounded-lg bg-[#fff8fb] px-2 py-1 text-[10px] font-bold text-[#765562]">{v.sku}</span>)}{p.variants.length>6&&<span className="px-1 py-1 text-[10px] text-[#8d6878]">+{p.variants.length-6}</span>}</div></div>)}</div></div>}
    </section>
    <aside className="space-y-4"><section className="pt-card p-4 sm:p-5"><h2 className="font-bold text-[#4d2938]">Resumen antes de confirmar</h2><div className="mt-4 grid grid-cols-2 gap-2"><Metric label="Productos nuevos" value={preview.newProducts}/><Metric label="A actualizar" value={preview.updatedProducts}/><Metric label="Variantes nuevas" value={preview.newVariants}/><Metric label="Variantes a actualizar" value={preview.updatedVariants}/></div><div className="mt-3 rounded-xl bg-[#fff8fb] p-3 text-xs text-[#765562]"><strong>{columns.length}</strong> columnas detectadas. El agrupamiento usa <strong>Identificador de URL + datos del producto</strong>; no corta el SKU por guiones.</div>{preview.duplicateSkus.length>0&&<div className="mt-3 rounded-xl bg-[#fff3f4] p-3 text-xs font-semibold text-[#a94658]">SKU duplicados: {preview.duplicateSkus.join(", ")}</div>}{parseErrors.map(e=><div key={e} className="mt-3 rounded-xl bg-[#fff3f4] p-3 text-xs font-semibold text-[#a94658]">{e}</div>)}<button onClick={confirm} disabled={!products.length||parseErrors.length>0||loading} className="pt-button-primary mt-4 w-full px-4">{loading?"Importando…":"Confirmar importación"}</button></section>
      {result&&<section className="pt-card p-4 sm:p-5"><h2 className="font-bold text-[#4d2938]">Resultado</h2>{result.errors?.length?<div className="mt-3 space-y-2">{result.errors.map(e=><p key={e} className="rounded-xl bg-[#fff3f4] p-3 text-xs font-semibold text-[#a94658]">{e}</p>)}</div>:<div className="mt-3 space-y-1 text-sm text-[#765562]"><p>Nuevos: <strong>{result.products_new??0}</strong> productos / <strong>{result.variants_new??0}</strong> variantes</p><p>Actualizados: <strong>{result.products_updated??0}</strong> productos / <strong>{result.variants_updated??0}</strong> variantes</p></div>}</section>}
    </aside>
  </div>
}
function Metric({label,value}:{label:string;value:number}){return <div className="rounded-xl bg-[#fff8fb] p-3"><p className="text-[9px] font-bold uppercase tracking-wide text-[#9a7a88]">{label}</p><p className="mt-1 text-xl font-extrabold text-[#4d2938]">{value}</p></div>}
