"use server";
import { revalidatePath } from "next/cache";
import { createClient } from "@/lib/supabase/server";
import { syncTiendanubeStock } from "@/lib/tiendanube-stock";
function refresh(id:string){revalidatePath(`/productos/${id}`);revalidatePath("/productos");revalidatePath("/stock");revalidatePath("/")}
const nullable=(v:FormDataEntryValue|null)=>{const s=String(v??"").trim();return s||null};
export async function updateProduct(formData:FormData){const id=String(formData.get("product_id")??"");if(!id)return;const supabase=await createClient();const {error}=await supabase.from("products").update({name:String(formData.get("name")??"").trim(),code:nullable(formData.get("code")),description:nullable(formData.get("description")),category:nullable(formData.get("category")),minimum_stock:Number(formData.get("minimum_stock")??0),current_cost:Number(formData.get("current_cost")??0),image_url:nullable(formData.get("image_url")),visible:formData.get("visible")==="on",published:formData.get("published")==="on",active:formData.get("active")==="on"}).eq("id",id);if(error)throw new Error(error.message);refresh(id)}
export async function createVariant(formData:FormData){const productId=String(formData.get("product_id")??"");if(!productId)return;const supabase=await createClient();const {error}=await supabase.from("product_variants").insert({product_id:productId,name:String(formData.get("name")??"").trim(),sku:nullable(formData.get("sku")),base_quantity:Number(formData.get("base_quantity")??0),price:Number(formData.get("price")??0),promo_price:Number(formData.get("promo_price")??0)||null,cost:Number(formData.get("cost")??0)||null,shipping_weight_g:Number(formData.get("shipping_weight_g")??0)||null,height_cm:Number(formData.get("height_cm")??0)||null,width_cm:Number(formData.get("width_cm")??0)||null,depth_cm:Number(formData.get("depth_cm")??0)||null,visible:formData.get("visible")==="on"});if(error)throw new Error(error.message);await syncTiendanubeStock().catch((e)=>console.error("[auto-stock] nueva variante",e));refresh(productId)}
export async function updateVariant(formData:FormData){const productId=String(formData.get("product_id")??"");const variantId=String(formData.get("variant_id")??"");if(!productId||!variantId)return;const supabase=await createClient();const {error}=await supabase.from("product_variants").update({name:String(formData.get("name")??"").trim(),sku:nullable(formData.get("sku")),base_quantity:Number(formData.get("base_quantity")??0),price:Number(formData.get("price")??0),promo_price:Number(formData.get("promo_price")??0)||null,cost:Number(formData.get("cost")??0)||null,shipping_weight_g:Number(formData.get("shipping_weight_g")??0)||null,height_cm:Number(formData.get("height_cm")??0)||null,width_cm:Number(formData.get("width_cm")??0)||null,depth_cm:Number(formData.get("depth_cm")??0)||null,active:formData.get("active")==="on",visible:formData.get("visible")==="on"}).eq("id",variantId);if(error)throw new Error(error.message);await syncTiendanubeStock().catch((e)=>console.error("[auto-stock] variante",e));refresh(productId)}
export async function createRecipe(formData:FormData){const productId=String(formData.get("product_id")??"");if(!productId)return;const supabase=await createClient();const {error}=await supabase.from("recipes").insert({output_product_id:productId,name:`Receta de ${String(formData.get("product_name")??"producto")}`,output_quantity_base:Number(formData.get("output_quantity_base")??0),status:"ACTIVA"});if(error)throw new Error(error.message);await syncTiendanubeStock().catch((e)=>console.error("[auto-stock] receta",e));refresh(productId)}
export async function addRecipeItem(formData:FormData){const productId=String(formData.get("product_id")??"");const recipeId=String(formData.get("recipe_id")??"");const ingredientId=String(formData.get("ingredient_product_id")??"");if(!productId||!recipeId||!ingredientId||ingredientId===productId)return;const supabase=await createClient();const {error}=await supabase.from("recipe_items").insert({recipe_id:recipeId,ingredient_product_id:ingredientId,quantity_base:Number(formData.get("quantity_base")??0),notes:nullable(formData.get("notes"))});if(error)throw new Error(error.message);await syncTiendanubeStock().catch((e)=>console.error("[auto-stock] ingrediente receta",e));refresh(productId)}
export async function removeRecipeItem(formData:FormData){const productId=String(formData.get("product_id")??"");const itemId=String(formData.get("item_id")??"");if(!productId||!itemId)return;const supabase=await createClient();const {error}=await supabase.from("recipe_items").delete().eq("id",itemId);if(error)throw new Error(error.message);await syncTiendanubeStock().catch((e)=>console.error("[auto-stock] quitar ingrediente",e));refresh(productId)}
