import { notFound } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { getCurrentProfile } from "@/lib/auth";
import { formatDateTime,formatMoney,formatQuantity } from "@/lib/format";
import PageHeader from "@/components/ui/page-header";
import ProductImage from "@/components/ui/product-image";
import VariantManager from "@/components/products/variant-manager";
import RecipeManager from "@/components/products/recipe-manager";
import StockAdjustmentButton from "@/components/stock/stock-adjustment-button";
import { updateProduct } from "./actions";

export default async function ProductPage({params}:{params:Promise<{id:string}>}){
 const{id}=await params;const supabase=await createClient();const profile=await getCurrentProfile();
 const[productRes,variantsRes,recipeRes,optionsRes,movementsRes]=await Promise.all([
  supabase.from("product_stock_overview").select("id,name,code,description,category,product_kind,inventory_mode,base_unit,on_hand,reserved,available_base,minimum_stock,current_cost,image_url,visible,published,active,tiendanube_product_id,tiendanube_handle,tiendanube_last_sync_at").eq("id",id).maybeSingle(),
  supabase.from("product_variants").select("id,name,sku,base_quantity,price,promo_price,cost,shipping_weight_g,height_cm,width_cm,depth_cm,tiendanube_variant_id,tiendanube_stock,active,visible").eq("product_id",id).order("base_quantity",{ascending:false}),
  supabase.from("recipes").select("id,name,output_quantity_base,status,waste_percentage").eq("output_product_id",id).eq("status","ACTIVA").maybeSingle(),
  supabase.from("products").select("id,name,base_unit,current_cost").eq("active",true).order("name"),
  supabase.from("inventory_movements").select("id,movement_type,on_hand_delta,reserved_delta,reason,reference_type,created_at").eq("product_id",id).order("created_at",{ascending:false}).limit(12),
 ]);
 const product=productRes.data;if(!product)notFound();const recipe=recipeRes.data;let recipeItems:Array<{id:string;quantity_base:number|string;notes:string|null;ingredient:{id:string;name:string;base_unit:string}|null}>=[];
 if(recipe){const{data:raw}=await supabase.from("recipe_items").select("id,ingredient_product_id,quantity_base,notes").eq("recipe_id",recipe.id).order("created_at");const options=optionsRes.data??[];const byId=new Map(options.map(o=>[o.id,o]));recipeItems=(raw??[]).map(i=>({id:i.id,quantity_base:i.quantity_base,notes:i.notes,ingredient:byId.get(i.ingredient_product_id)??null}))}
 const canEdit=profile?.role==="ADMIN";const canAdjust=profile?.role==="ADMIN"||profile?.role==="OPERADOR";const hasPhysical=product.inventory_mode!=="DERIVADO";
 return <main className="pt-page"><PageHeader eyebrow={kindLabel(product.product_kind)} title={product.name} description={`${product.code||product.tiendanube_handle||"Sin código"} · ${modeLabel(product.inventory_mode)}`} actions={hasPhysical&&canAdjust?<StockAdjustmentButton productId={product.id} productName={product.name} unit={product.base_unit} current={Number(product.on_hand??0)}/>:undefined}/>
 <section className="mb-4 grid grid-cols-2 gap-3 xl:grid-cols-4"><Metric label="Físico" value={hasPhysical?`${formatQuantity(product.on_hand)} ${product.base_unit}`:"—"}/><Metric label="Reservado" value={hasPhysical?`${formatQuantity(product.reserved)} ${product.base_unit}`:"—"}/><Metric label="Disponible" value={`${formatQuantity(product.available_base)} ${product.base_unit}`} strong/><Metric label="Costo actual" value={Number(product.current_cost)>0?formatMoney(product.current_cost):"Sin cargar"}/></section>
 <div className="grid min-w-0 gap-4 xl:grid-cols-[1.55fr_.85fr]"><div className="min-w-0 space-y-4"><VariantManager productId={product.id} unit={product.base_unit} variants={variantsRes.data??[]} canEdit={canEdit}/>{(product.inventory_mode==="DERIVADO"||product.inventory_mode==="PRODUCIDO")&&<RecipeManager productId={product.id} productName={product.name} unit={product.base_unit} recipe={recipe} items={recipeItems} options={optionsRes.data??[]} canEdit={canEdit} mode={product.inventory_mode}/>}<section className="pt-card overflow-hidden"><div className="border-b border-[#f2e0e8] px-4 py-4 sm:px-5"><h2 className="font-bold text-[#3e2833]">Movimientos recientes</h2><p className="mt-0.5 text-xs text-[#896b78]">El inventario no se modifica sin dejar historial.</p></div>{(movementsRes.data??[]).length===0?<div className="p-6 text-sm text-[#80616f]">Todavía no hay movimientos registrados.</div>:<div className="divide-y divide-[#f5e7ed]">{(movementsRes.data??[]).map(m=><div key={m.id} className="flex items-center gap-3 px-4 py-3 sm:px-5"><div className="min-w-0 flex-1"><p className="text-sm font-bold text-[#3e2833]">{movementLabel(m.movement_type)}</p><p className="mt-0.5 text-xs text-[#987b88]">{m.reason||m.reference_type||"Movimiento"} · {formatDateTime(m.created_at)}</p></div><div className="shrink-0 text-right text-xs font-extrabold"><p className={Number(m.on_hand_delta)>=0?"text-[#36785b]":"text-[#aa4558]"}>{Number(m.on_hand_delta)===0?"":`${Number(m.on_hand_delta)>0?"+":""}${formatQuantity(m.on_hand_delta)}`}</p>{Number(m.reserved_delta)!==0&&<p className="text-[#ad416f]">res {Number(m.reserved_delta)>0?"+":""}{formatQuantity(m.reserved_delta)}</p>}</div></div>)}</div>}</section></div>
 <aside className="min-w-0 space-y-4"><section className="pt-card p-4 sm:p-5"><div className="flex items-start gap-4"><ProductImage src={product.image_url} alt={product.name} size="lg"/><div className="min-w-0"><h2 className="font-bold text-[#3e2833]">Ficha del producto</h2><p className="mt-1 text-xs leading-5 text-[#80616f]">{product.image_url?"Imagen vinculada por URL.":"Sin imagen. El CSV actual no trae columna de imagen; queda lista para sincronizar por API."}</p></div></div>{canEdit?<form action={updateProduct} className="mt-5 space-y-3"><input type="hidden" name="product_id" value={product.id}/><Field label="Nombre"><input className="pt-input" name="name" defaultValue={product.name} required/></Field><div className="grid grid-cols-2 gap-3"><Field label="Código interno"><input className="pt-input" name="code" defaultValue={product.code??""}/></Field><Field label="Categoría"><input className="pt-input" name="category" defaultValue={product.category??""}/></Field></div><Field label="Descripción"><textarea className="pt-input min-h-28 resize-y" name="description" defaultValue={product.description??""}/></Field><Field label="URL de imagen"><input className="pt-input" type="url" name="image_url" defaultValue={product.image_url??""} placeholder="https://…"/></Field><div className="grid grid-cols-2 gap-3"><Field label={`Stock mínimo (${product.base_unit})`}><input className="pt-input" type="number" min="0" step="0.001" name="minimum_stock" defaultValue={String(product.minimum_stock??0)}/></Field><Field label="Costo base"><input className="pt-input" type="number" min="0" step="0.0001" name="current_cost" defaultValue={String(product.current_cost??0)}/></Field></div><div className="flex flex-wrap gap-4"><Check name="active" label="Activo" checked={product.active}/><Check name="visible" label="Visible" checked={product.visible}/><Check name="published" label="Publicado" checked={product.published}/></div><button className="pt-button-primary w-full px-4">Guardar ficha</button></form>:<p className="mt-4 text-xs text-[#80616f]">Solo ADMIN puede editar la ficha.</p>}</section>
 <section className="pt-card p-4 sm:p-5"><h2 className="font-bold text-[#3e2833]">Tiendanube</h2><div className="mt-4 space-y-3 text-xs"><InfoRow k="Identificador URL" v={product.tiendanube_handle||"No vinculado"}/><InfoRow k="Product ID" v={product.tiendanube_product_id||"Pendiente de API"}/><InfoRow k="Última sync" v={product.tiendanube_last_sync_at?formatDateTime(product.tiendanube_last_sync_at):"Nunca"}/></div><button disabled className="mt-4 min-h-11 w-full rounded-xl border border-[#eee0e6] bg-[#faf7f9] px-3 text-xs font-bold text-[#ad9aa3]">Conectar Tiendanube</button></section></aside></div></main>
}
function Metric({label,value,strong}:{label:string;value:string;strong?:boolean}){return <div className={`rounded-2xl border p-4 ${strong?"border-[#edbfd2] bg-[#fff0f6]":"border-[#efd8e2] bg-white"}`}><p className="text-[10px] font-bold uppercase tracking-wide text-[#917380]">{label}</p><p className={`mt-1.5 text-xl font-extrabold sm:text-2xl ${strong?"text-[#ad416f]":"text-[#3e2833]"}`}>{value}</p></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="pt-label">{label}</span>{children}</label>}
function Check({name,label,checked}:{name:string;label:string;checked:boolean}){return <label className="flex items-center gap-2 text-xs font-bold text-[#80616f]"><input type="checkbox" name={name} defaultChecked={checked}/>{label}</label>}
function InfoRow({k,v}:{k:string;v:string}){return <div className="flex items-start justify-between gap-3"><span className="text-[#8d6878]">{k}</span><strong className="max-w-[65%] break-all text-right text-[#4d2938]">{v}</strong></div>}
function kindLabel(v:string){return({INSUMO:"Materia prima",MIX:"Mix",ELABORADO:"Elaborado",COMBO:"Combo"} as Record<string,string>)[v]??v}function modeLabel(v:string){return({PROPIO:"Stock propio",DERIVADO:"Por componentes",PRODUCIDO:"Producido"} as Record<string,string>)[v]??v}function movementLabel(v:string){return({PURCHASE:"Compra",SALE:"Venta",RESERVATION:"Reserva",RELEASE:"Reserva liberada",ADJUSTMENT:"Ajuste",STOCK_COUNT:"Conteo físico",PRODUCTION_IN:"Producción ingresada",PRODUCTION_OUT:"Ingrediente consumido"} as Record<string,string>)[v]??v}
