"use client";
import Link from "next/link";
import { useMemo,useState } from "react";
import { Icon } from "@/components/ui/icons";
import ProductImage from "@/components/ui/product-image";
import { formatQuantity } from "@/lib/format";

type Product={id:string;name:string;code:string|null;description:string|null;product_kind:string;inventory_mode:string;base_unit:string;on_hand:number|string|null;reserved:number|string|null;available_base:number|string|null;minimum_stock:number|string|null;active:boolean;image_url:string|null;category:string|null;visible:boolean;published:boolean;tiendanube_handle:string|null};
const filterOptions=[["TODOS","Todos"],["INSUMO","Materias primas"],["MIX","Mixes"],["ELABORADO","Elaborados"],["COMBO","Combos"]] as const;
export default function ProductList({products}:{products:Product[]}){const[query,setQuery]=useState("");const[filter,setFilter]=useState<(typeof filterOptions)[number][0]>("TODOS");const filtered=useMemo(()=>products.filter(p=>{const q=query.trim().toLowerCase();if(q&&!`${p.name} ${p.code??""} ${p.category??""} ${p.tiendanube_handle??""}`.toLowerCase().includes(q))return false;return filter==="TODOS"||p.product_kind===filter}),[products,query,filter]);return <section className="pt-card overflow-hidden"><div className="border-b border-[#f2e0e8] p-3 sm:p-4"><div className="relative"><Icon name="search" className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[#a58a96]"/><input value={query} onChange={e=>setQuery(e.target.value)} className="pt-input pl-9" placeholder="Buscar producto, SKU padre o categoría…"/></div><div className="pt-scrollbar-none mt-3 flex gap-2 overflow-x-auto">{filterOptions.map(([k,l])=><button key={k} onClick={()=>setFilter(k)} className={`shrink-0 rounded-full px-3 py-1.5 text-xs font-bold ${filter===k?"bg-[#d65f91] text-white":"bg-[#fff1f7] text-[#895f72]"}`}>{l}</button>)}</div></div>{filtered.length===0?<div className="p-10 text-center text-sm text-[#80616f]">No hay productos para mostrar.</div>:<div className="divide-y divide-[#f5e7ed]">{filtered.map(p=>{const critical=p.inventory_mode!=="DERIVADO"&&Number(p.minimum_stock)>0&&Number(p.available_base)<=Number(p.minimum_stock);return <Link href={`/productos/${p.id}`} key={p.id} className="block p-4 transition hover:bg-[#fffafd] sm:p-5"><div className="flex items-start gap-3"><ProductImage src={p.image_url} alt={p.name}/><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="min-w-0 truncate font-bold text-[#3e2833]">{p.name}</p><span className="rounded-full bg-[#fff0f6] px-2 py-0.5 text-[10px] font-extrabold text-[#ad416f]">{kindLabel(p.product_kind)}</span>{critical&&<span className="rounded-full bg-[#fbecef] px-2 py-0.5 text-[10px] font-extrabold text-[#aa4558]">STOCK BAJO</span>}{!p.active&&<span className="rounded-full bg-[#f3f0f2] px-2 py-0.5 text-[10px] font-extrabold text-[#8c7680]">INACTIVO</span>}</div><p className="mt-0.5 truncate text-xs text-[#987b88]">{p.code||p.tiendanube_handle||"Sin código"} · {p.category||modeLabel(p.inventory_mode)}</p><p className="mt-1 line-clamp-1 text-xs text-[#8d6878]">{p.description||modeLabel(p.inventory_mode)}</p></div><Icon name="arrow" className="mt-1 h-4 w-4 shrink-0 text-[#b69aa7]"/></div><div className="mt-3 grid grid-cols-3 gap-2"><Value label="Físico" value={p.inventory_mode==="DERIVADO"?"—":`${formatQuantity(p.on_hand)} ${p.base_unit}`}/><Value label="Reservado" value={p.inventory_mode==="DERIVADO"?"—":`${formatQuantity(p.reserved)} ${p.base_unit}`}/><Value label="Disponible" value={`${formatQuantity(p.available_base)} ${p.base_unit}`} strong/></div></Link>})}</div>}</section>}
function Value({label,value,strong}:{label:string;value:string;strong?:boolean}){return <div className="min-w-0 rounded-xl bg-[#fffafd] px-2.5 py-2"><p className="text-[9px] font-bold uppercase tracking-wide text-[#a18692]">{label}</p><p className={`mt-0.5 truncate text-sm font-extrabold ${strong?"text-[#ad416f]":"text-[#4a303b]"}`}>{value}</p></div>}
function kindLabel(v:string){return({INSUMO:"Materia prima",MIX:"Mix",ELABORADO:"Elaborado",COMBO:"Combo"} as Record<string,string>)[v]??v}function modeLabel(v:string){return({PROPIO:"Stock propio",DERIVADO:"Por componentes",PRODUCIDO:"Producido"} as Record<string,string>)[v]??v}
