import { addRecipeItem, createRecipe, removeRecipeItem } from "@/app/(dashboard)/productos/[id]/actions";
import { formatQuantity } from "@/lib/format";

type Recipe = { id: string; output_quantity_base: number | string; name: string } | null;
type Item = { id: string; quantity_base: number | string; notes: string | null; ingredient: { id: string; name: string; base_unit: string } | null };
type Option = { id: string; name: string; base_unit: string };

export default function RecipeManager({ productId, productName, unit, recipe, items, options, canEdit, mode }: { productId: string; productName: string; unit: string; recipe: Recipe; items: Item[]; options: Option[]; canEdit: boolean; mode: string }) {
  return <section className="pt-card overflow-hidden">
    <div className="border-b border-[#f2e0e8] px-4 py-4 sm:px-5"><h2 className="font-bold text-[#3e2833]">Receta</h2><p className="mt-0.5 text-xs text-[#896b78]">{mode === "DERIVADO" ? "Define de qué stock depende este producto" : "Ingredientes que consume al producirlo"}</p></div>
    {!recipe ? <div className="p-4 sm:p-5"><p className="text-sm leading-6 text-[#80616f]">Todavía no hay una receta activa. Definí el rendimiento de una receta base.</p>{canEdit && <form action={createRecipe} className="mt-4 flex flex-col gap-3 sm:flex-row sm:items-end"><input type="hidden" name="product_id" value={productId}/><input type="hidden" name="product_name" value={productName}/><label className="flex-1"><span className="mb-1.5 block text-xs font-bold text-[#80616f]">Rendimiento de receta ({unit})</span><input className="pt-input" type="number" name="output_quantity_base" min="0.001" step="0.001" placeholder={unit === "g" ? "Ej. 1000" : "Ej. 1"} required/></label><button className="pt-button-primary px-4">Crear receta</button></form>}</div> : <>
      <div className="bg-[#fffafd] px-4 py-3 text-xs text-[#80616f] sm:px-5">Receta base: <strong className="text-[#4a303b]">{formatQuantity(recipe.output_quantity_base)} {unit}</strong></div>
      {items.length === 0 ? <div className="px-4 py-6 text-sm text-[#80616f] sm:px-5">Agregá los ingredientes que componen esta receta.</div> : <div className="divide-y divide-[#f5e7ed]">{items.map((item) => <div key={item.id} className="flex items-center gap-3 px-4 py-3 sm:px-5"><div className="min-w-0 flex-1"><p className="font-bold text-[#3e2833]">{item.ingredient?.name ?? "Ingrediente"}</p><p className="mt-0.5 text-xs text-[#987b88]">{formatQuantity(item.quantity_base)} {item.ingredient?.base_unit ?? ""}{item.notes ? ` · ${item.notes}` : ""}</p></div>{canEdit && <form action={removeRecipeItem}><input type="hidden" name="product_id" value={productId}/><input type="hidden" name="item_id" value={item.id}/><button className="rounded-lg px-2.5 py-1.5 text-xs font-bold text-[#aa4558] hover:bg-[#fbecef]">Quitar</button></form>}</div>)}</div>}
      {canEdit && <form action={addRecipeItem} className="grid gap-3 border-t border-[#f2e0e8] p-4 sm:grid-cols-[1fr_160px_1fr_auto] sm:items-end sm:p-5"><input type="hidden" name="product_id" value={productId}/><input type="hidden" name="recipe_id" value={recipe.id}/><label><span className="mb-1.5 block text-[10px] font-bold uppercase tracking-wide text-[#80616f]">Ingrediente</span><select className="pt-input" name="ingredient_product_id" required defaultValue=""><option value="" disabled>Elegir…</option>{options.filter((o)=>o.id!==productId).map((o)=><option key={o.id} value={o.id}>{o.name} ({o.base_unit})</option>)}</select></label><label><span className="mb-1.5 block text-[10px] font-bold uppercase tracking-wide text-[#80616f]">Cantidad</span><input className="pt-input" type="number" min="0.001" step="0.001" name="quantity_base" required/></label><label><span className="mb-1.5 block text-[10px] font-bold uppercase tracking-wide text-[#80616f]">Nota</span><input className="pt-input" name="notes" placeholder="Opcional"/></label><button className="pt-button-primary px-4">Agregar</button></form>}
    </>}
  </section>;
}
