"use client";
import { useState } from "react";

type SyncResult = {
  ok?: boolean; error?: string; tiendanubeProducts?: number; linkedProducts?: number; linkedVariants?: number; unmatchedVariants?: number; unlinkedProducts?: number; productsWithMultipleVariants?: number; imagesFound?: number; imagesUpdated?: number; productsWithoutImages?: number; imageFetchErrors?: number; variantsUpdated?: number; variantsArchived?: number; observationsSaved?: number; observationsWarning?: string | null;
  imageErrors?: Array<{ productId: string; status?: number; detail: string }>;
};

export function SyncCatalogButton() {
  const [loading,setLoading]=useState(false); const [result,setResult]=useState<SyncResult|null>(null); const [error,setError]=useState<string|null>(null);
  async function syncCatalog(){setLoading(true);setResult(null);setError(null);try{const response=await fetch("/api/tiendanube/sync-catalog",{method:"POST",headers:{Accept:"application/json"}});const text=await response.text();let data:SyncResult;try{data=JSON.parse(text)}catch{throw new Error(`Respuesta inválida. HTTP ${response.status}`)}setResult(data);if(!response.ok||data.ok===false)throw new Error(data.error||`Error HTTP ${response.status}`)}catch(err){setError(err instanceof Error?err.message:"No se pudo sincronizar")}finally{setLoading(false)}}
  return <div className="space-y-3"><button type="button" onClick={syncCatalog} disabled={loading} className="pt-button-primary px-4 text-sm">{loading?"Sincronizando…":"Sincronizar catálogo"}</button>{error&&<div className="rounded-xl border border-[#efc4ce] bg-[#fff7f8] p-3 text-sm text-[#a94658]"><strong>No se pudo sincronizar.</strong> {error}</div>}{result&&result.ok&&<div className="rounded-xl border border-[#cfe8db] bg-[#f5fbf8] p-4 text-sm text-[#315e4a]"><p className="font-black">Catálogo actualizado</p><div className="mt-2 grid gap-1.5 sm:grid-cols-2"><p>Productos TN: <strong>{result.tiendanubeProducts??0}</strong></p><p>Vinculados: <strong>{result.linkedProducts??0}</strong></p><p>Opciones vinculadas: <strong>{result.linkedVariants??0}</strong></p><p>Presentaciones antiguas archivadas: <strong>{result.variantsArchived??0}</strong></p><p>Productos TN sin vínculo: <strong>{result.unlinkedProducts??0}</strong></p><p>Con múltiples variantes: <strong>{result.productsWithMultipleVariants??0}</strong></p><p>Imágenes encontradas: <strong>{result.imagesFound??0}</strong></p><p>Observaciones guardadas: <strong>{result.observationsSaved??0}</strong></p></div>{result.observationsWarning&&<p className="mt-2 rounded-lg bg-[#fff4dc] p-2 text-xs text-[#80633a]">Aviso: {result.observationsWarning}</p>}</div>}</div>;
}
