import Link from "next/link";
import {notFound} from "next/navigation";
import {createClient} from "@/lib/supabase/server";
import {formatDateTime,formatMoney} from "@/lib/format";
import PrintActions from "./print-actions";

export default async function RemitoPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{precios?:string}>}){
 const{id}=await params;const sp=await searchParams;const withPrices=sp.precios!=="0";const supabase=await createClient();
 const[{data:o},{data:items},{data:brandRes}]=await Promise.all([supabase.from("orders").select("*").eq("id",id).maybeSingle(),supabase.from("order_items").select("id,product_name_snapshot,variant_name_snapshot,sku_snapshot,quantity,unit_price,total_price").eq("order_id",id).order("created_at"),supabase.from("app_settings").select("value").eq("key","brand_identity").maybeSingle()]);
 if(!o)notFound();const address=typeof o.shipping_address==="string"?o.shipping_address:(o.shipping_address?.address||o.shipping_address?.line||"");const brand=(brandRes?.value&&typeof brandRes.value==="object"?brandRes.value:{}) as {logo_url?:string};
 return <main className="bg-[#f7f1f4] p-3 sm:p-6 print:min-h-0 print:bg-white print:p-0"><div className="no-print mx-auto mb-4 flex max-w-4xl flex-wrap gap-2"><Link href={`/ventas/${id}`} className="pt-button-secondary inline-flex items-center px-4 text-sm">← Volver a la venta</Link><Link href={`/ventas/${id}/remito?precios=${withPrices?"0":"1"}`} className="pt-button-secondary inline-flex items-center px-4 text-sm">{withPrices?"Ocultar precios":"Mostrar precios"}</Link><PrintActions/></div>
 <article className="mx-auto max-w-4xl rounded-[24px] bg-white p-6 shadow-[0_18px_50px_rgba(70,40,53,.08)] sm:p-10 print:max-w-none print:rounded-none print:p-0 print:shadow-none">
  <header className="flex items-start justify-between gap-6 border-b-2 border-[#efd6e1] pb-6 print:border-black"><div className="flex items-center gap-4"><img src={brand.logo_url||"/brand/logo.svg"} alt="Pecán Tigre" className="h-14 w-14 object-contain"/><div><p className="text-xs font-extrabold tracking-[.24em] text-[#a83f6d] print:text-black">PECÁN TIGRE</p><h1 className="mt-1 text-3xl font-extrabold text-[#4d2938] print:text-black">Remito</h1><p className="mt-1 text-xs text-[#8d6878] print:text-black">Detalle de entrega · No es factura ni comprobante fiscal</p></div></div><div className="text-right"><p className="text-xs font-bold uppercase text-[#8d6878] print:text-black">Pedido</p><p className="text-xl font-extrabold text-[#4d2938] print:text-black">#{o.order_number}</p><p className="mt-2 text-xs text-[#8d6878] print:text-black">{formatDateTime(o.created_at)}</p></div></header>
  <section className="grid gap-4 border-b border-[#eadce2] py-6 sm:grid-cols-2 print:grid-cols-2 print:border-black"><Info label="Cliente" value={o.customer_name_snapshot||"—"}/><Info label="Teléfono" value={o.customer_phone_snapshot||"—"}/><Info label="Dirección" value={address||"—"}/><Info label="Entrega" value={o.shipping_method||"A coordinar"}/></section>
  <section className="py-6"><h2 className="text-sm font-extrabold uppercase tracking-wide text-[#4d2938]">Productos</h2><div className="mt-4 space-y-2">{(items??[]).map(i=><div key={i.id} className="grid grid-cols-[42px_1fr_auto] items-start gap-3 rounded-xl bg-[#fff8fb] p-3 print:rounded-none print:border-b print:border-gray-300 print:bg-white"><div className="text-center font-extrabold text-[#a83f6d] print:text-black">{i.quantity}×</div><div><p className="font-bold text-[#4d2938] print:text-black">{i.product_name_snapshot}</p><p className="mt-0.5 text-xs text-[#8d6878] print:text-black">{i.variant_name_snapshot||"Presentación"}</p></div>{withPrices&&<p className="text-right font-extrabold text-[#4d2938] print:text-black">{formatMoney(i.total_price,o.currency)}</p>}</div>)}</div>
  {withPrices&&<div className="mt-6 ml-auto max-w-sm space-y-2 border-t border-[#eadce2] pt-4 text-sm print:border-black"><div className="flex justify-between"><span>Productos</span><strong>{formatMoney(o.subtotal??0,o.currency)}</strong></div><div className="flex justify-between"><span>Envío</span><strong>{formatMoney(o.shipping_charge??o.shipping_cost??0,o.currency)}</strong></div><div className="flex justify-between border-t border-[#eadce2] pt-2 text-lg print:border-black"><strong>Total a pagar</strong><strong>{formatMoney(o.total,o.currency)}</strong></div><div className="flex justify-between text-xs text-[#80616f] print:text-black"><span>Medio de pago</span><strong>{o.payment_method||"A coordinar"}</strong></div><div className="flex justify-between text-xs text-[#80616f] print:text-black"><span>Estado</span><strong>{o.payment_status||"PENDIENTE"}</strong></div></div>}</section>
  <footer className="mt-12 grid grid-cols-2 gap-12 text-center text-xs text-[#8d6878] print:text-black"><div className="border-t border-[#bfaab3] pt-2 print:border-black">Entregado por</div><div className="border-t border-[#bfaab3] pt-2 print:border-black">Recibido / firma</div></footer>
 </article></main>
}
function Info({label,value}:{label:string;value:string}){return <div><p className="text-[10px] font-bold uppercase tracking-wide text-[#9a7a88] print:text-black">{label}</p><p className="mt-1 text-sm font-bold text-[#4d2938] print:text-black">{value}</p></div>}
