"use client";
import {useState} from "react";

type Brand={logo_url?:string;favicon_url?:string};
export default function BrandSettings({initial}:{initial:Brand}){
 const [logo,setLogo]=useState(initial.logo_url||"");const[favicon,setFavicon]=useState(initial.favicon_url||"");const[saving,setSaving]=useState(false);const[message,setMessage]=useState("");
 async function upload(kind:"logo"|"favicon",file:File){setSaving(true);setMessage("");try{const fd=new FormData();fd.set("kind",kind);fd.set("file",file);const res=await fetch("/api/settings/brand",{method:"POST",body:fd});const data=await res.json() as {ok?:boolean;url?:string;error?:string};if(!res.ok||!data.ok||!data.url)throw new Error(data.error||"No se pudo subir la imagen");if(kind==="logo")setLogo(data.url);else{setFavicon(data.url);const link=document.querySelector<HTMLLinkElement>('link[rel="icon"]');if(link)link.href=`${data.url}?v=${Date.now()}`;}setMessage("Identidad actualizada correctamente");}catch(e){setMessage(e instanceof Error?e.message:"Error al subir") }finally{setSaving(false)}}
 return <div className="grid gap-4 sm:grid-cols-2"><UploadCard title="Logo" value={logo||"/brand/logo.svg"} kind="logo" onUpload={upload} disabled={saving}/><UploadCard title="Favicon" value={favicon||"/brand/favicon.svg"} kind="favicon" onUpload={upload} disabled={saving}/>{message&&<p className="sm:col-span-2 text-xs font-bold text-[#6d5cff]">{message}</p>}</div>
}
function UploadCard({title,value,kind,onUpload,disabled}:{title:string;value:string;kind:"logo"|"favicon";onUpload:(k:"logo"|"favicon",f:File)=>void;disabled:boolean}){return <div className="rounded-2xl border border-[#f0dfe7] bg-[#fffafd] p-4"><div className="flex items-center gap-3"><img src={value} alt={title} className="h-14 w-14 rounded-2xl border border-[#eddde5] bg-white object-contain p-1.5"/><div><p className="text-sm font-black text-[#3e2833]">{title}</p><p className="mt-1 text-[11px] text-[#8b7580]">Máximo 2 MB</p></div></div><label className="pt-button-secondary mt-3 flex cursor-pointer items-center justify-center px-3 text-xs">{disabled?"Subiendo…":`Cambiar ${title.toLowerCase()}`}<input type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml,image/x-icon" className="hidden" disabled={disabled} onChange={e=>{const f=e.target.files?.[0];if(f)onUpload(kind,f)}}/></label></div>}
